ID ученика (PupilID)
Имя (FirstName)
Фамилия (LastName)
Дата рождения (DateOfBirth)
Пол (Gender)
Адрес электронной почты (Email)
Номер телефона (PhoneNumber)
Город (City)
Страна (Country)
Дата начала обучения (EnrollmentDate)
Дата окончания обучения (GraduationDate)
Преподаватель (Teacher)